#!/bin/bash
# Script to take screenshot, upload to Imgur anonymously, and copy the url to clipboard

# Load webss.conf
. /bin/webss/webss.conf

# Command line option flags
window=false
delay=false
delayValue=0

while getopts ":wd:" opt; do
	case ${opt} in
	  w ) window=true
	    ;;
	  d ) delay=true && delayValue=$OPTARG
		;;
	  \? ) echo "Usage: cmd [-w][-d SECONDS]" && exit 1
	    ;;
	esac 
done

# Use current date as filename
curDate=$(date)
curDateNoSpace="$(echo -e "${curDate}" | tr -d '[:space:]')"
imgExtension=".png"
imgName=$curDateNoSpace$imgExtension

# mkdir if screenshots directory doesn't exist
imgDirectory="/bin/webss/screenshots/"
if [[ ! -d $imgDirectory ]]
then
	mkdir /bin/webss/screenshots
fi

imgSavePath=$imgDirectory$imgName


screenshotOptions=''

if [ $window = true ]
then
  screenshotOptions='--window'
fi
if [ $delay = true ]
then
	screenshotOptions=$screenshotOptions' --delay='$delayValue
fi

gnome-screenshot $screenshotOptions --file="$imgSavePath"


# Upload Image and get link
raw_url=$(curl --header "Authorization: Client-ID ${CLIENT_ID}" --request POST 'https://api.imgur.com/3/image' --form "image=@${imgSavePath}" | jq '.data.link')

# Strip " from string
url=$(echo $raw_url | tr -d '",')

# Copy link to clipboard
echo $url | xclip -selection c

